### ISSUE TITLE
Heroku permissions

### ISSUE THREAD

**Issue by istumpf** [g5search/devops-access#105]
I'm trying to setup: https://github.com/g5search/g5-news-and-events-service

But when I run the command to get a database dump, I see the following message:
```
heroku pg:pull DATABASE_URL g5-news-and-events-service_development --app g5-news-and-events-service
 ▸    You do not have permission to view addon resources on g5-news-and-events-service. You need to have the deploy or operate permission on
 ▸    this app.
```

**Comment by markbluhm** [comment]
g5-news-and-events-service_development isn't a herokuapp. We dont' have a dev/dummy database that I know of, you just create the DB locally. If you need production data just drop _development from your command

**Comment by istumpf** [comment]
I tried without the `_development` got the same error:
```
heroku pg:pull DATABASE_URL g5-news-and-events-service --app g5-news-and-events-service
 ▸    You do not have permission to view addon resources on g5-news-and-events-service. You need to have the deploy or operate permission on
 ▸    this app.
```

**Comment by randyleighton** [comment]
closing this up I see you have access.
