### ISSUE TITLE
Heroku permission: News & events - staging

### ISSUE THREAD

**Issue by istumpf** [g5search/devops-access#108]
I need to deploy News & Events on staging but I will need some permissions to be able to access the app. 

Dashboard URL:
https://dashboard.heroku.com/apps/g5-news-and-events-staging
Permission error message: 
![image](https://user-images.githubusercontent.com/8162419/66677576-51720600-ec40-11e9-9da4-64f4dd9e7a4f.png)

**Comment by randyleighton** [comment]
should have the invite now to use that app
