### ISSUE TITLE
Access to ZeBlanc CLS on heroku

### ISSUE THREAD

**Issue by JoeyJRob** [g5search/devops-access#109]
Does the heroku app still exist for the following?
https://g5-cls-irxrei0s-ze-blanc-ss.herokuapp.com/

If so, may I have access to it?

Thanks,
joey

**Comment by markbluhm** [comment]
That app does exist, I will work on access for you.

**Comment by markbluhm** [comment]
It is broken, fyi, maybe just dynos turned off. We can work on that after access

**Comment by markbluhm** [comment]
Oops didn't mean to reopen
