### ISSUE TITLE
Heroku access to Location Data Pusher?

### ISSUE THREAD

**Issue by ryanmcadler** [g5search/devops-access#19]
Could I trouble you for access to LDP?

https://g5-location-pusher-prod.herokuapp.com/

Thanks in advance.

**Comment by randyleighton** [comment]
you should have invites for
INFO[0009] TeamInvitationCreate                          role=admin team=centralized-apps user=ryan.mcadler@getg5.com
INFO[0025] TeamInvitationCreate                          role=admin team=qa-analytics user=ryan.mcadler@getg5.com

**Comment by ryanmcadler** [comment]
Thank you!
