### ISSUE TITLE
James github access to IMC repo

### ISSUE THREAD

**Issue by Kirksten3** [g5search/devops-access#23]
Github account email: james.rutledge37@yahoo.com
username: KrombopulosJames

**Comment by randyleighton** [comment]
he should have invite to "read" access on the cms
https://github.com/g5search/imc/invitations

We can change to write if you need later

**Comment by randyleighton** [comment]
I will leave this open for now until we are sure that this is the right access level

**Comment by randyleighton** [comment]
gonna close this up if you need more let me know.
