### ISSUE TITLE
Bigquery access to project containing cCMS

### ISSUE THREAD

**Issue by Kirksten3** [g5search/devops-access#24]
content-staging-f6ab

**Comment by randyleighton** [comment]
Ok I gave access to compute engine admin and g5dev(multi role) to content production. Reopen this or new issue if any more needed.

**Comment by randyleighton** [comment]
access to project probably changed because of the content prod getting changed. I put access on the `Content` folder this time as `g5dev`.

**Comment by randyleighton** [comment]
I also put `Compute Admin` on the `content` folder.
