### ISSUE TITLE
Shannon M to get access to all Honeybadger, github & bit.  (CMS/Sites team)

### ISSUE THREAD

**Issue by mikelindaas** [g5search/devops-access#26]

**Comment by randyleighton** [comment]
I sent a request for github name to add to the product/qa team
I sent invite to honeybadger for orion/engineering teams
Heroku will be centralized, so probably not much access needed, if any specific apps come up please submit request for those.

**Comment by randyleighton** [comment]
i got her github account and added to product team there.

**Comment by randyleighton** [comment]
ok so i talked to jeff and ricker, if we have a need for bitbucket later we can talk about it then. with the changes to the centralized cms, we are not going to need to give out heroku/bitbucket access anymore most likely.
