### ISSUE TITLE
Access to Gemfury for James

### ISSUE THREAD

**Issue by Kirksten3** [g5search/devops-access#37]
james.rutledge@getg5.com

Setting up IMC env and needs to pull down some gems. What's the process once access is given as well? Is it an env var that gets set?

**Comment by randyleighton** [comment]
I sent an invite from gemfury account to james.rutledge37@yahoo.com
I think he has to authorize his github with that, then it should just be able to pull down. I dont think there is any env var or anything

**Comment by Kirksten3** [comment]
@randyleighton Looks like he doesn't have access to the G5dev account still. But his personal account exists up in Gem Fury. Can he get added to the g5dev account now?

**Comment by randyleighton** [comment]
this is done. He accepted the invite and once he did I added him as a collaborator with download access.

**Comment by Kirksten3** [comment]
Thanks!
