### ISSUE TITLE
content-prod access users for cloud sql

### ISSUE THREAD

**Issue by mmitchellg5** [g5search/devops-access#64]
![Screen Shot 2019-08-30 at 11 55 15 AM](https://user-images.githubusercontent.com/6045075/64045006-18148980-cb1d-11e9-9a7d-3e167864f5ef.png)

**Comment by randyleighton** [comment]
added some cloudsql.users permission to g5dev for now. make sure nothing is created that is expected to be permanent unless thats done in terraform
