### ISSUE TITLE
Amazon S3: Create bucket for dcms-postgres-backup

### ISSUE THREAD

**Issue by dreuss** [g5search/devops-access#65]
I would like to have a bucket created to drop dCMS databases in.  It would be great to have it with similar permissions / access as the `dcls-postgres-backup` bucket.  Thank you.

**Comment by randyleighton** [comment]
Dave this is in process, I will let you know soon

**Comment by randyleighton** [comment]
good to go. I created the bucket, and added permissions in S3 to the policy that gives access.
