### ISSUE TITLE
Create New and Events project on Honeybadger

### ISSUE THREAD

**Issue by boniattirodrigo** [g5search/devops-access#72]
I'm working on a story to configure Honeybadger on [News and Events](https://github.com/g5search/g5-news-and-events-service). When trying to create a new project there I'm getting a message saying that I have reached the limit on the number of projects.

**Comment by markbluhm** [comment]
I can drop the client app creater project but need to get into the admin account. I'll update soon

**Comment by markbluhm** [comment]
g5-news-and-events project created, api key placed on production NAE.
Remember to use HONEYBADGER_ENV env var
