### ISSUE TITLE
Access to Runbook

### ISSUE THREAD

**Issue by marvinahv** [g5search/devops-access#81]
Hi. I'm looking for the docs in how to deploy the Vendor Leads Pull Service to staging.

And I need access to this page (or the repo) https://github.com/g5search/runbook/blob/gcp/content/gcp/set-up-gcp.md.

Thank you!

**Comment by randyleighton** [comment]
I updated the runbook acces for Codeminer team to write. Please submit any PRs to the Devops channel before merging anything there.

**Comment by marvinahv** [comment]
Great. Thanks again, @randyleighton !
