### ISSUE TITLE
GCP billing account access

### ISSUE THREAD

**Issue by mmitchellg5** [g5search/devops-access#87]
```
There was an error while loading /billing/00822D-64D988-0818D4?organizationId=1037889784460.

You are missing at least one of the following required permissions:
Project

resourcemanager.projects.get
Resource

billing.accounts.get
Check that the project and resource IDs are valid and you have permissions to access them. Learn more

Troubleshoot
```
I'm trying to diagnose large bills for ~august 29 and sept 9 in bigquery in the data-lake project — thinking of exporting billing info to bigquery for this purpose like shown here
https://cloud.google.com/billing/docs/how-to/export-data-bigquery
but I dont have the necessary authorization
https://console.cloud.google.com/navigation-error;errorUrl=%2Fbilling%2F00822D-64D988-0818D4%3ForganizationId%3D1037889784460/permissions

**Comment by randyleighton** [comment]
this is done
