### ISSUE TITLE
Keeper Access for email g5dev@g5searchmarketing.com

### ISSUE THREAD

**Issue by Kirksten3** [g5search/devops-access#99]
Can I get access to the keeper record for the email listed above? I was told it was in the devops keeper account. 

Thanks

**Comment by markbluhm** [comment]
Hey @Kirksten3 I need to double check but I'm pretty sure IT manages access to that account.

**Comment by Kirksten3** [comment]
@riverblufftrail Told me that Devops did. In hindsight I may not actually need the credentials. I'm just going to end up giving it access to all the google my business stuff. So it might get spammed by that. All I really need is to give it access and assign the email

**Comment by randyleighton** [comment]
i shared the email and okta, enjoy
